services:
  postgres:
    image: postgres:18-alpine
    container_name: node-study-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: node-study
      POSTGRES_PASSWORD: node-study
      POSTGRES_DB: lp_service
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
